name: Deploy para AWS Lambda

on:
  push:
    branches:
      - main  # Aciona o deploy quando houver push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Empacotar código
        run: zip -r lambda_function.zip main.py

      - name: Fazer deploy no AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name apiTeste \
            --zip-file fileb://lambda_function.zip